FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy only development requirements
COPY requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.dev.txt

COPY . .

ENTRYPOINT ["python", "main.py"]